### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by numairawan** [SergiX44/twscraper#5]
HI, is this still working? because i tried your example and its not showing any tweets.

**Comment by sergix44** [comment]
Yes, it should, just tried with: 
![image](https://user-images.githubusercontent.com/4172890/157041130-9010fb3b-d3cc-45ba-bd2a-ca677f407bfa.png)

**Comment by numairawan** [comment]
I tried the same example and getting nothing in result.

![image](https://user-images.githubusercontent.com/62851858/157761057-f076ec20-ed89-41bf-a771-ab848e703ebc.png)

**Comment by numairawan** [comment]
I did run the code in cli but same, empty result. Any special php extension required? Btw i am using php 8.0.1.

**Comment by sergix44** [comment]
In the example 
```
->onChunk(function (array $tweets, int $totalTweets) { // optional
		//...
	}, true) // than flush? (useflul when processing lot of tweets and avoid memory exhausted errors)
```

when set the flush to true, after the call to the closure you will get an empty array when calling the getTweets.
As written in the readme that useful when parsing thousands of tweets.
Use the code like in my screen if you dont need that feature.
